name: fedora-dist
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/fedora.yml'
      - '!fedora/**'
  workflow_dispatch:
  repository_dispatch:
    types: fedora-build

jobs:
  build:
    name: Building fedora docker images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dist:
          - {
              name: fedora-40,
              os: fedora,
              symbol: 40,
              platforms: "linux/amd64,linux/arm64"
            }
          - {
              name: fedora-41,
              os: fedora,
              symbol: 41,
              platforms: "linux/amd64,linux/arm64"
            }
          - {
              name: fedora-42,
              os: fedora,
              symbol: 42,
              platforms: "linux/amd64,linux/arm64"
            }
          # - {
          #     name: fedora-rawhide,
          #     os: fedora,
          #     symbol: rawhide,
          #     platforms: "linux/amd64,linux/arm64"
          #   }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        id: prepare
        run: |
          DIST_NAME=${{ matrix.dist.name }}
          USER_NAME=flameshot-org
          REPO_NAME=ci-building
          IMAGE_NAME=${{ matrix.dist.os }}/${{ matrix.dist.symbol }}
          REGISTRY_NAME=quay.io
          TAGS="${REGISTRY_NAME}/${USER_NAME}/${REPO_NAME}:${DIST_NAME}"
          echo "build_args=VERSION=${DIST_NAME}" >> $GITHUB_OUTPUT
          echo "image-name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: ./${{ steps.prepare.outputs.image-name }}
          file: ./${{ steps.prepare.outputs.image-name }}/Dockerfile
          platforms: ${{ matrix.dist.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tags }}
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
      - name: Clear
        if: always()
        run: |
          rm -rf ${HOME}/.docker/config.json
